export const API_ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  GUEST_ID_REQUIRED: 'GUEST_ID_REQUIRED',
  INVALID_GUEST_ID: 'INVALID_GUEST_ID',
  INVALID_SEARCH_FILTER: 'INVALID_SEARCH_FILTER',
  INVALID_TERM_UUIDS: 'INVALID_TERM_UUIDS',
  INVALID_ANNOUNCEMENT_UUIDS: 'INVALID_ANNOUNCEMENT_UUIDS',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  ADMIN_ROLE_REQUIRED: 'ADMIN_ROLE_REQUIRED',
  NOT_FOUND: 'NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  CLUB_NOT_FOUND: 'CLUB_NOT_FOUND',
  RECRUITMENT_NOT_FOUND: 'RECRUITMENT_NOT_FOUND',
  MANAGER_REQUEST_NOT_FOUND: 'MANAGER_REQUEST_NOT_FOUND',
  VERIFICATION_REQUEST_NOT_FOUND: 'VERIFICATION_REQUEST_NOT_FOUND',
  CONFLICT: 'CONFLICT',
  CLUB_ALREADY_HAS_MANAGER: 'CLUB_ALREADY_HAS_MANAGER',
  PENDING_MANAGER_REQUEST_EXISTS: 'PENDING_MANAGER_REQUEST_EXISTS',
  RECRUITMENT_ALREADY_EXISTS_FOR_MONTH: 'RECRUITMENT_ALREADY_EXISTS_FOR_MONTH',
  MANAGER_REQUEST_ALREADY_PROCESSED: 'MANAGER_REQUEST_ALREADY_PROCESSED',
  VERIFICATION_REQUEST_ALREADY_PROCESSED: 'VERIFICATION_REQUEST_ALREADY_PROCESSED',
  CLUB_ALREADY_VERIFIED: 'CLUB_ALREADY_VERIFIED',
  PENDING_VERIFICATION_REQUEST_EXISTS: 'PENDING_VERIFICATION_REQUEST_EXISTS',
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
} as const

export type ApiErrorCode = (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES]

export type ApiErrorResponse = {
  error: {
    code: ApiErrorCode
    message: string
    details?: unknown
    requestId?: string
  }
}

type CreateApiErrorBodyArgs = {
  code: ApiErrorCode
  message: string
  details?: unknown
  requestId?: string
}

export function createApiErrorBody({
  code,
  message,
  details,
  requestId,
}: CreateApiErrorBodyArgs): ApiErrorResponse {
  const error: ApiErrorResponse['error'] = {
    code,
    message,
  }

  if (details !== undefined) {
    error.details = details
  }
  if (requestId) {
    error.requestId = requestId
  }

  return { error }
}
