name: Deploy-prod

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/_deploy.yml
    with:
      ocir_repository: allclear-prod/allclear-web
      dockerfile: Dockerfile
    secrets:
      OCI_AUTH_TOKEN: ${{ secrets.OCI_AUTH_TOKEN }}
